export const PLAYLISTS_FETCH_PLAYLISTS_BEGIN = 'PLAYLISTS_FETCH_PLAYLISTS_BEGIN';
export const PLAYLISTS_FETCH_PLAYLISTS_SUCCESS = 'PLAYLISTS_FETCH_PLAYLISTS_SUCCESS';
export const PLAYLISTS_FETCH_PLAYLISTS_FAILURE = 'PLAYLISTS_FETCH_PLAYLISTS_FAILURE';
export const PLAYLISTS_FETCH_PLAYLISTS_DISMISS_ERROR = 'PLAYLISTS_FETCH_PLAYLISTS_DISMISS_ERROR';
